# Generated by Django 2.1.4 on 2019-01-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nomeMae', models.CharField(max_length=100, verbose_name='Nome da mãe')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('grupoAmigo', models.CharField(choices=[('Prédio', 'Prédio'), ('Escola', 'Escola')], max_length=50, verbose_name='Grupo de amigo')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero da caixa')),
                ('etiqueta', models.CharField(max_length=50, verbose_name='Etiqueta')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEmprestimo', models.DateField(verbose_name='Data do emprestimo')),
                ('dataDevolucao', models.DateField(verbose_name='Data da devolução')),
            ],
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroEdicao', models.IntegerField(default=0, verbose_name='Numero de edição')),
                ('ano', models.IntegerField(default=0, verbose_name='Ano')),
            ],
        ),
    ]
