# Generated by Django 2.1.4 on 2019-01-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amigo',
            options={'verbose_name': 'Amigo', 'verbose_name_plural': 'Amigos'},
        ),
        migrations.AlterModelOptions(
            name='caixa',
            options={'verbose_name': 'Caixa', 'verbose_name_plural': 'Caixas'},
        ),
        migrations.AlterModelOptions(
            name='colecao',
            options={'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterModelOptions(
            name='revista',
            options={'verbose_name': 'Revista', 'verbose_name_plural': 'Revistas'},
        ),
        migrations.AddField(
            model_name='colecao',
            name='revista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Revista'),
            preserve_default=False,
        ),
    ]
