# Generated by Django 2.1.4 on 2019-01-10 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190110_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='revista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Revista'),
        ),
    ]
