# Generated by Django 2.1.4 on 2019-01-10 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190110_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='colecao',
        ),
        migrations.AddField(
            model_name='colecao',
            name='revista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Revista'),
            preserve_default=False,
        ),
    ]
