# Generated by Django 2.1.4 on 2019-01-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190110_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='revista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Revista'),
        ),
    ]
