# Generated by Django 2.1.4 on 2019-01-10 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190110_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='caixa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Caixa'),
            preserve_default=False,
        ),
    ]
